version: "3"

networks:
  monitoring:

services:
  backend:
    build:
      context: .
      dockerfile: ./random_generator/Dockerfile
    env_file:
      - "random_generator/tests/.env"
    networks:
      - monitoring

  frontend:
    build:
      context: .
      dockerfile: ./random_generator_front_end/Dockerfile
    environment:
      STREAMLIT_CLIENT_TOOLBAR_MODE: "viewer"
      RANDOM_GENERATOR_FRONTEND_BACKEND_URL: "http://backend:8000"
    ports:
      - "8000:8000"
    expose:
      - 8000
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.51.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - 9090
    ports:
      - "9090:9090"
    command: --config.file=/etc/prometheus/prometheus.yml
    networks:
      - monitoring
