name: Testing random_generator

on: push

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.0'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run black check
      run: poetry run black --check .
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.0'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run flake8 check
      run: poetry run flake8 --extend-ignore I001,I005,WPS437,DAR301,E501,WPS436,WPS318,WPS319,S311,WPS112,WPS338,WPS420,WPS463,WPS458 --count --max-complexity 10 random_generator
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.0'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run mypy check
      run: poetry run mypy .
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.0'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run pytest check
      run: poetry run pytest -vv --cov="random_generator" .
      env:
        RANDOM_GENERATOR_HOST: "0.0.0.0"
